- name: docker build and push
  hosts: localhost

  tasks:
    - name: Build Docker Image
      command: docker build -t calculator.jar .
      args:
        chdir: /var/lib/jenkins/workspace/SPE_MiniProject

    - name: tag image
      command: docker tag calculator.jar ashutoshd99/calculator:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: ashutoshd99
        password: asdfrtqwe

    - name: push image
      command: docker push ashutoshd99/calculator:latest
